# Generated by Django 5.0.6 on 2024-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_product_salesreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='month',
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='sales',
            field=models.IntegerField(),
        ),
    ]
