# Generated by Django 5.0.6 on 2024-07-19 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_salesreport_month_alter_salesreport_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='month_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
